/*
 * generated by Xtext
 */
package fr.inria.diverse.kcvl.ui.contentassist

import fr.inria.diverse.kcvl.ui.contentassist.AbstractKCVLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class KCVLProposalProvider extends AbstractKCVLProposalProvider {
}
