/*
 * generated by Xtext
 */
package fr.inria.diverse.kcvl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KCVLRuntimeModule extends fr.inria.diverse.kcvl.AbstractKCVLRuntimeModule {

}
