/*
* generated by Xtext
*/
package fr.inria.diverse.kcvl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class KCVLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
