/*
* generated by Xtext
*/
package fr.inria.diverse.kcvl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.diverse.kcvl.services.KCVLGrammarAccess;

public class KCVLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private KCVLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.diverse.kcvl.parser.antlr.internal.InternalKCVLParser createParser(XtextTokenStream stream) {
		return new fr.inria.diverse.kcvl.parser.antlr.internal.InternalKCVLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "VPackage";
	}
	
	public KCVLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(KCVLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
