/*
* generated by Xtext
*/
package org.varymde.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CvlmappingvaribilitychoiceAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/varymde/parser/antlr/internal/InternalCvlmappingvaribilitychoice.tokens");
	}
}
