/*
 * generated by Xtext
 */
package fr.inria.diverse.kcvl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KCVLUiModule extends fr.inria.diverse.kcvl.ui.AbstractKCVLUiModule {
	public KCVLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
