/*
 * generated by Xtext
 */
package org.varymde;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CvlmappingvaribilitychoiceRuntimeModule extends org.varymde.AbstractCvlmappingvaribilitychoiceRuntimeModule {

}
