/*
* generated by Xtext
*/
package org.varymde.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.varymde.services.CvlmappingvaribilitychoiceGrammarAccess;

public class CvlmappingvaribilitychoiceParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CvlmappingvaribilitychoiceGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.varymde.parser.antlr.internal.InternalCvlmappingvaribilitychoiceParser createParser(XtextTokenStream stream) {
		return new org.varymde.parser.antlr.internal.InternalCvlmappingvaribilitychoiceParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RestrictionRuleset";
	}
	
	public CvlmappingvaribilitychoiceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CvlmappingvaribilitychoiceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
