/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.kcvl.validation

import org.eclipse.xtext.validation.Check
import org.omg.cvl.BaseModelHandle
import org.omg.cvl.CvlPackage.Literals
import org.eclipse.capella.vp.kcvl.KCvlUtils

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class KCVLValidator extends AbstractKCVLValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					KCVLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

@Check
	def checkReferencedEObjectExists(BaseModelHandle obj) {
		println(obj.reference)
		if (obj.reference == null)
			try {
				KCvlUtils::resolve(obj)
				error("Cannot resolve reference to EObject", Literals::BASE_MODEL_HANDLE__REFERENCE_STRING)
			} catch (Exception e) {
				e.printStackTrace
				error("Cannot  reference to EObject: " + e.message, Literals::BASE_MODEL_HANDLE__REFERENCE_STRING)	
			}	
	}
	
}
