/*
 * generated by Xtext
 */
package fr.inria.diverse.kcvl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.diverse.kcvl.ui.internal.KCVLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KCVLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KCVLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KCVLActivator.getInstance().getInjector(KCVLActivator.FR_INRIA_DIVERSE_KCVL_KCVL);
	}
	
}
