/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.kcvl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KCVLStandaloneSetup extends KCVLStandaloneSetupGenerated {

	def static void doSetup() {
		new KCVLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
